const _courses = [
  {
    id: 'course-1',
    title: 'Introduction to Web Development',
    description: 'Learn the basics of HTML, CSS, and JavaScript to build your first websites.',
    duration: 2,
    instructor: 'Alice Johnson',
  },
  {
    id: 'course-2',
    title: 'Advanced JavaScript',
    description: 'Deep dive into modern JavaScript features including ES6+, closures, and async programming.',
    duration: 4,
    instructor: 'David Smith',
  },
  {
    id: 'course-3',
    title: 'React Fundamentals',
    description: 'Understand the core concepts of React including components, hooks, and state management.',
    duration: 3,
    instructor: 'Emma Davis',
  },
  {
    id: 'course-4',
    title: 'Node.js for Beginners',
    description: 'Get started with server-side JavaScript using Node.js and Express.',
    duration: 3,
    instructor: 'Michael Thompson',
  },
  {
    id: 'course-5',
    title: 'Python Programming',
    description: 'Learn Python syntax, data structures, and build small projects with it.',
    duration: 6,
    instructor: 'Sarah Lee',
  },
  {
    id: 'course-6',
    title: 'Data Structures and Algorithms',
    description: 'Understand essential algorithms and data structures for technical interviews.',
    duration: 8,
    instructor: 'James Anderson',
  },
  {
    id: 'course-7',
    title: 'UI/UX Design Principles',
    description: 'Explore the fundamentals of user interface and user experience design.',
    duration: 6,
    instructor: 'Laura Martin',
  },
  {
    id: 'course-8',
    title: 'Mobile App Development with Flutter',
    description: 'Build beautiful cross-platform mobile apps using Flutter and Dart.',
    duration: 6,
    instructor: 'Chris Wilson',
  },
  {
    id: 'course-9',
    title: 'DevOps Basics',
    description: 'Learn the foundations of CI/CD, Docker, and cloud deployment strategies.',
    duration: 10,
    instructor: 'Olivia White',
  },
  {
    id: 'course-10',
    title: 'Machine Learning Essentials',
    description: 'Get introduced to machine learning concepts and build your first ML models.',
    duration: 10,
    instructor: 'Daniel Kim',
  },
  {
    id: 'course-11',
    title: 'Database Design and SQL',
    description: 'Master relational database concepts and SQL for querying data.',
    duration: 8,
    instructor: 'Sophia Clark',
  },
  {
    id: 'course-12',
    title: 'TypeScript from Scratch',
    description: 'Learn TypeScript to write safer and more robust JavaScript applications.',
    duration: 8,
    instructor: 'Benjamin Lewis',
  },
  {
    id: 'course-13',
    title: 'Cybersecurity Fundamentals',
    description: 'Understand common threats, vulnerabilities, and best practices in cybersecurity.',
    duration: 3,
    instructor: 'Chloe Walker',
  },
  {
    id: 'course-14',
    title: 'Agile Project Management',
    description: 'Explore agile methodologies like Scrum and Kanban for team productivity.',
    duration: 4,
    instructor: 'Ethan Hall',
  },
  {
    id: 'course-15',
    title: 'Cloud Computing with AWS',
    description: 'Learn core AWS services and how to deploy applications in the cloud.',
    duration: 6,
    instructor: 'Grace Robinson',
  }
];

export default _courses;